srent:

  wx:
    app-id: wx233751238b7f98f3
    app-secret: 348930af73634662021d4e045a710cf2
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify

    key-path: xxxxx

  #通知相关配置
  notify:
    mail:
      # 邮件通知配置
      enable: false
      host: smtp.exmail.qq.com
      username: ex@ex.com.cn
      password: XXXXXXXXXXXXX
      sendfrom: ex@ex.com.cn
      sendto: ex@qq.com

    # 短消息模版通知配置
    sms:
      enable: false
      appid: 111111111
      appkey: xxxxxxxxxxxxxx
      template:
        - name: paySucceed
          templateId: 156349
        - name: captcha
          templateId: 156433
        - name: ship
          templateId: 158002
        - name: refund
          templateId: 159447

    # 微信模版通知配置
    # 微信模版用于通知客户或者运营者，注意配置格式；template-name，template-templateId 请参考 NotifyType 枚举值
    wx:
      enable: false
      template:
        - name: paySucceed
          templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: captcha
          templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: ship
          templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        - name: refund
          templateId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx



  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、aliyun、tencent、qiniu
    active: qiniu
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
      address: http://192.168.10.107:8081/wx/storage/fetch/
    #    address: http://localhost:8081/wx/storage/fetch/

    # 阿里云对象存储配置信息
    aliyun:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      accessKeyId: 111111
      accessKeySecret: xxxxxx
      bucketName: srent
    # 腾讯对象存储配置信息
    # 请参考 https://cloud.tencent.com/document/product/436/6249
    tencent:
      secretId: 111111
      secretKey: xxxxxx
      region: xxxxxx
      bucketName: srent
    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://qiniu.csmaxwell.xyz
      accessKey: AncbDnAejYZlX0SciSKJIHgAYOo6zxnDU7WBIZc4
      secretKey: Zmz5qmF5FmzgkfAYoo2kXLOCcfLT6qM_wGJuOXEZ
      bucketName: wx