srent:

  wx:
    app-id: wx233751238b7f98f3
    app-secret: 348930af73634662021d4e045a710cf2
    mch-id: 111111
    mch-key: xxxxxx
    notify-url: http://www.example.com/wx/order/pay-notify

    key-path: xxxxx

  # 对象存储配置
  storage:
    # 当前工作的对象存储模式，分别是local、qiniu
    active: qiniu
    # 本地对象存储配置信息
    local:
      storagePath: storage
      # 这个地方应该是wx模块的WxStorageController的fetch方法对应的地址
#      address: http://192.168.10.107:8081/wx/storage/fetch/
      address: http://localhost:8081/wx/storage/fetch/

    # 七牛云对象存储配置信息
    qiniu:
      endpoint: http://qiniu.csmaxwell.xyz
      accessKey: AncbDnAejYZlX0SciSKJIHgAYOo6zxnDU7WBIZc4
      secretKey: Zmz5qmF5FmzgkfAYoo2kXLOCcfLT6qM_wGJuOXEZ
      bucketName: wx